### ISSUE TITLE
installation error: during jupyter nbextension install

### ISSUE THREAD

**Issue by xavyjs** [allegroai/trains-jupyter-plugin#1]
While following the installation steps, 

while `sudo jupyter nbextension install --py trains-jupyter-plugin`

I get the following error
![jupyter_plugin_error](https://user-images.githubusercontent.com/5502309/60161549-5eeab800-982a-11e9-88ea-7718550677ac.png)

Current jupyter version: 4.4.0
python version: 3.6.5

**Comment by bmartinn** [comment]
It looks like the trains-jupyter-plugin package is not installed:

I imagine what happened was:
`pip install trains-jupyter-plugin`
Installed the package on the default python version (for example 3.6)

While jupyter was installed on a different python version (python 2.7 for example)
As can be seen in your attached trace-back, `jupyter` is looking for the `trains-jupyter-plugin` in the python2.7 packages...

@xavyjs did that solve the problem?
