### ISSUE TITLE
Can't disable_check_xsrf

### ISSUE THREAD

**Issue by mrmathematica** [allegroai/trains-jupyter-plugin#2]
This probably comes from source upstream in the form of https://github.com/sat28/githubcommit/issues/17

Could you please properly fix this jupyter plugin so that when installing it, there is no need to do:

echo 'c.NotebookApp.disable_check_xsrf = True' >> ~/.jupyter/jupyter_notebook_config.py

**Comment by bmartinn** [comment]
Hi @mrmathematica , 
Please check if the problem is solved with v0.2.1 :)

`$ pip install trains-jupyter-plugin==0.2.1`

**Comment by mrmathematica** [comment]
solved with v0.2.1! Thumbs up.
