### ISSUE TITLE
clearml-jupyter-plugin package name in docs does not exist

### ISSUE THREAD

**Issue by dlangerm** [allegroai/trains-jupyter-plugin#3]
The docs page for this package is not up to date.

[this](https://allegro.ai/clearml/docs/docs/integrations/integration_jupyter.html) link tells me to run `pip install clearml-jupyter-plugin` but that does not exist. 

Apparently this package needs the name to be updated.

**Comment by bmartinn** [comment]
Hi @dlangerm 
Actually this Jupyter Notebook is somewhat deprecated 😄  , as JupyterLab now includes git integration, hence there is no need for a special Jupyter notebook plugin.

If you are using `clearml` no special plugin is needed, `cleaml` will automatically log the entire Jupyter notebook for you (both as python script and as ipynb / html). Together with `clearml-agent` you are also able to execute the notebook as a python script on any machine connected to your `cleaml-server`

**Comment by dlangerm** [comment]
So I found this not to be the case both when executing jupyter notebooks through VS-code and when executing in the browser. ClearML only picked up the wrapper code executing the notebook and not the notebook itself, which is what led me to this plugin as I had assumed it may fix my issues.
